name: Create Pull Request

on:
  push:
    branches:
      - "review/изменения дашбордов" # Замените на имя вашей ветки

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Автоматический коммит
        title: 'Новый Pull Request'
        body: 'Описание Pull Request'
        branch: 'имя_ветки_для_pull_request'
        delete-branch: true
        labels: |
          automated pr

