name: Pull Request Action

on:
  push:
    branches:
      - review/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const branchName = '${{ github.ref_name }}';
            const result = await github.rest.pulls.create({
              owner,
              repo,
              title: `Pull Request from ${branchName} into main`,
              head: branchName,
              base: 'main',
              body: [
                'Это автоматически созданный Pull Request',
                '[actions/github-script](https://github.com/actions/github-script).',
                'Предлагается добавление изменений из',
                `${branchName} в основную ветку.`
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['review', 'automated pr']
            });

