name: Create Pull Request

on:
  push:
    branches:
      - 'review/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Автоматический коммит
        title: 'Изменения в дашбордах'
        body: 'изменения в дашбордах'
        branch: ${{ github.head_ref }}
        base: 'main'
        delete-branch: true
        labels: |
          automated pr
